<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subscription_susbscribe_email</name>
   <tag></tag>
   <elementGuidId>f6a1bae0-3dc8-413f-bcb1-565837e404df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#susbscribe_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='susbscribe_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39ad1f84-935c-46fc-9ef3-f8420b2a55e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>56991d30-9929-4926-9c2b-77e3537208ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>susbscribe_email</value>
      <webElementGuid>ca013374-1ddc-4b65-ba6c-5974de897d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your email address</value>
      <webElementGuid>db61a167-6ce4-4e6e-9c42-61fddd334f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;susbscribe_email&quot;)</value>
      <webElementGuid>6958f5ab-730b-47ea-bff0-8834ecc50573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='susbscribe_email']</value>
      <webElementGuid>4cfb6e77-ca59-4dce-8a9a-17ceba829176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div/div/div/div[2]/div/form/input[2]</value>
      <webElementGuid>e485125d-c31a-4554-a0da-3ee8fbd5c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>70fb4cd3-cc0b-46c6-bc18-69505cd6078b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'susbscribe_email' and @placeholder = 'Your email address']</value>
      <webElementGuid>2875c7ad-a09c-4ce0-a49f-738c21fa2b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
