<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IndiaUnited StatesCanadaAustraliaIsr_09757b</name>
   <tag></tag>
   <elementGuidId>31e62c45-c37f-4bab-b50c-4a0a955d20de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#country</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ef1e7b19-0a72-4f99-a737-e3704aedb2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>b1f5e88b-d95e-40b4-b509-9ab887ddbc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>420ea73d-3577-4a00-a281-3a5ed8922bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>c9f6dec5-ddf5-45a7-b883-e03093575854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>94bdbf57-2f20-432c-be56-efd60ac4ffdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								India
								United States
								Canada
								Australia
								Israel
								New Zealand
								Singapore
							</value>
      <webElementGuid>2e5a72fa-a108-4503-b4aa-9dbf43162b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country&quot;)</value>
      <webElementGuid>38855150-ce16-42c8-8bb0-b1ebc0afe643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='country']</value>
      <webElementGuid>41986c0e-f3d4-498a-8162-8cc5645935e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[6]/select</value>
      <webElementGuid>a0757d4e-720a-4c99-8a71-db4b1b2ba03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>10da9c23-8d0e-492c-9041-159481865474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>d06e97b9-746d-49fd-8274-0d909712e88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/select</value>
      <webElementGuid>369c93f8-7f67-4676-98d5-d5f81aab9060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'country' and @name = 'country' and (text() = '
								India
								United States
								Canada
								Australia
								Israel
								New Zealand
								Singapore
							' or . = '
								India
								United States
								Canada
								Australia
								Israel
								New Zealand
								Singapore
							')]</value>
      <webElementGuid>7d062e09-c3d3-479e-bd4e-086dad4f68b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
