<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tshirts</name>
   <tag></tag>
   <elementGuidId>4c7f853a-f015-47fb-9382-80c25491dbd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Men']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Men > div.panel-body > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14f0e080-ed3d-4aa9-b6ff-427fe862ae87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category_products/3</value>
      <webElementGuid>45897fc0-61de-45da-b411-4be85ee56280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tshirts </value>
      <webElementGuid>9c25a2a0-148b-4bb2-87e7-b8f5390eda0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Men&quot;)/div[@class=&quot;panel-body&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>41649911-2e44-44cd-8c9f-2660f3a64ae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Men']/div/ul/li/a</value>
      <webElementGuid>2c790044-c001-4759-b144-99a752d01e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tshirts')]</value>
      <webElementGuid>e42df0c3-812c-421b-9cfd-8aceadf10654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saree'])[1]/following::a[2]</value>
      <webElementGuid>9c78475f-7667-4e5e-9191-d1c078eaeec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/preceding::a[1]</value>
      <webElementGuid>e98d2075-46c5-489d-bf83-893ef679637b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tshirts']/parent::*</value>
      <webElementGuid>4c64598c-f8fb-4495-86d4-f4c9c570350c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/category_products/3')]</value>
      <webElementGuid>71ab6b8d-007c-4650-9eb3-65276c182c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li/a</value>
      <webElementGuid>b4d1d658-0bb7-4aec-95a9-b80083144c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/category_products/3' and (text() = 'Tshirts ' or . = 'Tshirts ')]</value>
      <webElementGuid>63630699-c4bb-4411-ba9c-140d137eca28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
