<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration_expiry_month</name>
   <tag></tag>
   <elementGuidId>a6589ecb-f8ff-4d65-b4f8-c4bd6f3f7444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='expiry_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;expiry_month&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40b13b61-f2bf-4e1c-b93f-33508ec27ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control card-expiry-month</value>
      <webElementGuid>d5aa7869-69cf-4672-a110-ff994306d860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry_month</value>
      <webElementGuid>f2f9b5a1-359b-4545-b14d-f27764d551b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>expiry-month</value>
      <webElementGuid>1478c8cf-1ff8-4fa0-b282-3556064a4d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM</value>
      <webElementGuid>1c36338d-95fd-4e46-badf-cd8956614e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>696ca80c-7a0f-4ce9-9aa0-1f65e15db8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-4 form-group expiration&quot;]/input[@class=&quot;form-control card-expiry-month&quot;]</value>
      <webElementGuid>f675d289-b70d-43c5-b07b-349209389d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='expiry_month']</value>
      <webElementGuid>59966bd8-3976-4c59-a085-a3eb69650d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div[3]/div[2]/input</value>
      <webElementGuid>04b1f2b3-34aa-4e35-aa4f-c8a88c1e4a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>94249f64-d1a1-46d0-a950-d3be90794702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'expiry_month' and @placeholder = 'MM' and @type = 'text']</value>
      <webElementGuid>20d0ed63-091b-4219-a323-75ca25423d9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
