<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Get In Touch_contact-form</name>
   <tag></tag>
   <elementGuidId>2bbaaf02-7ec2-4303-a105-1d3a464d525a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-us-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='contact-us-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>83913e91-350c-4d96-9b31-8ff4d35bf7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-us-form</value>
      <webElementGuid>075fc6e0-6cdf-4e38-8c7f-6457c15e6664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/contact_us</value>
      <webElementGuid>522cb58d-a303-427c-b767-2a4fa9cc79a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact-form row</value>
      <webElementGuid>94ebfc12-7b5a-4739-9c55-f79903ba7541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact-form</value>
      <webElementGuid>241a8238-2238-4445-8fff-81d0d3dfb756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>75587801-883b-431c-ba97-889f6bda8e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-us-form&quot;)</value>
      <webElementGuid>be942868-d47e-48a4-8d29-550c219bae66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='contact-us-form']</value>
      <webElementGuid>7f5f230c-ae99-4b37-ab20-436e1b8cfaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-section']/form</value>
      <webElementGuid>9b854cd3-94d0-4dba-a569-2aeba232c78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get In Touch'])[1]/following::form[1]</value>
      <webElementGuid>71b93f52-d1fc-4910-9708-324fedd935cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::form[1]</value>
      <webElementGuid>bad63fb7-4ccf-4c4a-b940-413b668827ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback For Us'])[1]/preceding::form[1]</value>
      <webElementGuid>88cf68da-0a64-4aaf-ba09-a0787e489cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='feedback@automationexercise.com'])[1]/preceding::form[1]</value>
      <webElementGuid>56323ce3-2d9b-495b-9ff6-a4a9176ed14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>1dd5fe8f-a652-4bc2-b878-237eb2ed0f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'contact-us-form' and @name = 'contact-form']</value>
      <webElementGuid>bf6c5388-4bfc-4398-bdd9-d38f00a53014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
