<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>1e82120f-6847-4145-96ed-667ac1bc3d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.cart_quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-1']/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>60798388-d61c-4347-8ab3-74ec9da7917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_quantity</value>
      <webElementGuid>d2429fb3-c53e-4119-b942-31b6c9c3ba14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								1
							</value>
      <webElementGuid>9eb03675-0e40-45bd-8f08-453180dba1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1&quot;)/td[@class=&quot;cart_quantity&quot;]</value>
      <webElementGuid>1dfe21f8-3b65-48b3-b36c-76caa99202c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-1']/td[4]</value>
      <webElementGuid>dcdebf37-0943-4502-8437-5c03697f18b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Top'])[1]/following::td[2]</value>
      <webElementGuid>7650039d-4495-4094-88ba-7b7ecacfe102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::td[5]</value>
      <webElementGuid>8efa9bf3-ef8b-4747-a74b-72962a6eccdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/preceding::td[4]</value>
      <webElementGuid>3334a67a-c06c-46c6-9472-a18cba35a7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::td[9]</value>
      <webElementGuid>f4875a3b-0615-4efb-982f-85b9d925d705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[4]</value>
      <webElementGuid>cea80b4a-48a5-4e76-82fa-818e5101a355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
								1
							' or . = '
								1
							')]</value>
      <webElementGuid>bda44315-d6c1-41f7-96e7-2bca2ef368e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
