<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subscription_susbscribe_email</name>
   <tag></tag>
   <elementGuidId>8ca83ef5-5c04-4c4e-adee-3906310c5f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#susbscribe_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='susbscribe_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3dfbbfb-3bb3-4488-91a8-8ef62b7975bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c982d03d-b309-4360-91c8-507f185a8bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>susbscribe_email</value>
      <webElementGuid>9957f958-2c77-49f2-aeb2-ab510c6cad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your email address</value>
      <webElementGuid>86e4099f-5da9-451b-8cc8-04e62a971fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;susbscribe_email&quot;)</value>
      <webElementGuid>64cbe60d-7b95-4828-8e55-ab65bd2ab904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='susbscribe_email']</value>
      <webElementGuid>0059ce57-4341-4a0d-b948-328617687aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div/div/div/div[2]/div/form/input[2]</value>
      <webElementGuid>81784586-3626-4838-8865-f2cdd42efb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>51c6ce90-3be9-4f13-bf9b-5364f399642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'susbscribe_email' and @placeholder = 'Your email address']</value>
      <webElementGuid>c92b30de-864e-4538-a774-dfb595e611c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
