<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Blue Top_fa fa-times</name>
   <tag></tag>
   <elementGuidId>63a6410b-5eeb-4e3e-9cd3-e584652bfb39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-1']/td[6]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>18ea9ff8-5496-470d-999a-cb7cd98f3111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>45a27bb7-dbec-4bb4-b2d6-63c66a4ebee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1&quot;)/td[@class=&quot;cart_delete&quot;]/a[@class=&quot;cart_quantity_delete&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>e830b41f-d490-4dac-8911-c6d5630339c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-1']/td[6]/a/i</value>
      <webElementGuid>51b85e4b-736e-481b-b2fc-0285f58d0af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>5be10a78-99dd-4b77-8b6d-306dd86d48f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
